### ISSUE TITLE
Updated template files do not load in development

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1060]
They are only copied if the files didn't exist. This means they aren't updated when they've changed

https://github.com/pulibrary/marc_liberation/blob/590c0712fe4b04114c69ce9998c7e7238ebfb858/app/services/location_maps_generator_service.rb#L50

Should they just be copied every time? Do we have any reason to keep / edit local copies of these?

**Comment by christinach** [comment]
Closing this issue and quoting the comment from https://github.com/pulibrary/bibdata/pull/1135#issuecomment-802401119 `In the checkin we said to remove the tmpl files and keep only the .rb files. After looking into this I rejected it as an option. I'm quoting my note from slack I kept solid only the holding_library.tmpl file so that we don’t need to generate it every time. I rejected the idea of using the .rb files that we generate through the #generate method because they are being generated by retrieving data from the tables. With that said every time you start lando and you generate the .rb files using the tables from the database the tables would be empty and the generated .rb files would be empty. Unless you also call the alma api every time you start lando so that you populate the tables. We don’t want to call the alma api every time we run the app in development or test. So it is better to keep the tmpl files and use them through the #generate_from_templates method so that we will create the .rb files locally in case they don’t exist.
Also this Pr addresses the removal of the double label in the orangelight display and updates the Location::Holdings table in bibdata. It also improves the code by removing unused lines of code and the generation of a nil file.`

**Comment by hackartisan** [comment]
Delete https://github.com/pulibrary/bibdata/blob/590c0712fe4b04114c69ce9998c7e7238ebfb858/app/services/location_maps_generator_service.rb#L50 and make the copy force overwrite.

This will solve developer problems having mysterious test failures which 75% of the time are due to out of data translation maps.

**Comment by christinach** [comment]
closed by #1161
