### ISSUE TITLE
Figure out why we are getting triple location labels

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1079]
We would have expected double with the current data

**Comment by christinach** [comment]
We get a triple library label because we follow the concept from voyager. With Alma we can get the library and the location of the library without needing to add the library label in front of them. We need to refactor the generate method in the `LocationMapsGeneratorService` so that we create the locations template but without appending the library label in front of the holding label. 
I will open a new issue to work on that. https://github.com/pulibrary/bibdata/issues/1133
