### ISSUE TITLE
Run a full index for initial QA

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1154]
The process is run the publishing job for the full dump and then run the rake task once the files are ready. We might also want to delete the current index first just to have a clean start. Let's also do the scsb items.

**Comment by christinach** [comment]
The full reindex started t 2:46pm. I did not include the UPDATE_LOCATIONS=true flag because of https://github.com/pulibrary/bibdata/issues/1187. There are records with no holdings but the ones that have locations are indexed as expected. 
The holding locations have duplicate or triple strings because we updated the location to use the external_name. When https://github.com/pulibrary/bibdata/issues/1178 is done then we can proceed improving the location names https://github.com/pulibrary/bibdata/issues/1167.

**Comment by hackartisan** [comment]
@christinach every time I deploy I have to copy that one template map before I can run the index. I'm not sure why or what we can do to keep it so we don't need to do this. Do you have a sense of what will take care of that for us, or do we need a new issue here?

**Comment by christinach** [comment]
we have an issue yes. I was planning to do this after the flags. https://github.com/pulibrary/bibdata/issues/1168

**Comment by hackartisan** [comment]
👍🏻 thanks!

**Comment by hackartisan** [comment]
The full index clocked in at 21:10:06 elapsed.

**Comment by hackartisan** [comment]
this is done and swapped in.
