### ISSUE TITLE
Redesign location data pipeline

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1195]
We currently have a database, translation maps, and translation map templates. We've also thrown alma configuration into the mix as another source of data. The architecture has become difficult to reason about and small changes take a lot of time to get right.

Side note that in the unlikely event that we continue to use an "UPDATE_LOCATIONS" environment flag we should discuss whether it's needed for indexing events that are triggered from within the rails app -- the bibliographic#update controller action and the IncrementalIndexJob

**Comment by christinach** [comment]
@kevinreiss and I discussed yesterday to keep the UI so that we can display what locations exist but to remove any actions that allow to edit, update, create or delete any location or library through the UI https://github.com/pulibrary/bibdata/issues/1193. 
Also support the locations and libraries updates through json files that will exist in the code base. 

For any potential change we should update the files and with a rake task we would update production or development. This discussion happened so that I can proceed with https://github.com/pulibrary/bibdata/issues/1103

**Comment by hackartisan** [comment]
@christinach @kevinreiss I'm thinking whatever design we settle on should be documented with a diagram. If you want to work something up to help communicate this plan for the meeting that would probably be helpful.

**Comment by christinach** [comment]
This is a description based on the work I'm doing on #1103. https://docs.google.com/document/d/1acUlM073h_jaxi6IpTDTbW8UwNNPj1QeDJt1q7xg8kE/edit

**Comment by hackartisan** [comment]
We held some meetings, with notes recorded in the document linked above.

The decision was to move away from a database and to a json file in the repository that holds all the location data.

Any time a change is needed to the location data (labels, flags, mappings), an issue should be created and a PR issued for the change.

the locations gem should load the data into memory and deliver API responses from here instead of from a database.

Similarly, traject should load the data into memory for use in translation maps.

These migraiton steps will be ticketed separately; closing this issue.
