### ISSUE TITLE
Index temp locations

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1198]
we need to index 876$y 'Current library' and 876$z'Current location.' 

If 876$y and $z is different than the 852 $b and $c field (holding), then they need to be grouped in the new key in the holdings1_display field.
example: https://github.com/pulibrary/bibdata/issues/1198#issuecomment-946895244

mms_id to export: 99124695833506421

**Comment by mzelesky** [comment]
Possible approach:

In parsing a MARCXML record from the publishing job, evaluate all items under each holding (linked by the subfield 0 in the 876 and the subfield 8 in the 852). If the item's current location (876|y and 876|z) is the same as the holding location, store the item under that holding ID.

If the item's current location is different from the holding location (the item is in a temp location), create a 'fake' holding for that location and store the item under that fake holding. Any subsequent items in that current location found on the bib record that differ from their parent holding locations also get stored under that fake holding. The same process needs to happen for all location variances found.

This will also allow us to show the items under a holding, which is a feature from Voyager we had to abandon.

**Comment by mzelesky** [comment]
Observations on related holding fields (866, 867, 868) of holdings where temp locations are in play.

1) All items on a holding are in a temp location.
    No holdings statement is included in the AVA field.

2) Some items on a holding are in a temp location, others are in the permanent location.
    A holdings statement is included in the AVA field for the permanent location, even though some items in the range (ex. vol. 1-v. 8) are not at that location. This is somewhat misleading for the user.
    No holdings statement is included in the AVA field for the temp location.

Unless a different approach is taken about displaying item-level information in the record show page, there doesn't seem to be much choice in following the above pattern. This would mean the following can be implemented for the show page:

A. "Location has" will be displayed for holdings where items don't exist at all.
B. "Location has" will be displayed for holdings where there are all items in the permanent location.
C. "Location has" will be displayed for holdings where there are some items in the permanent location [this will be inaccurate since the temp location items will be shelved separately, but it's how Alma returns it in the AVA field].
D. "Location has" will not be displayed for holdings with items with locations that differ from the permanent location.

The "location has" statement is returned in the AVA fields (AVA $t), but it could also be indexed from the publishing jobs (the 866, 867, 868 fields).
