### ISSUE TITLE
Update fixtures for skipped holdings tests in traject config spec

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/bibdata#1246]
https://github.com/pulibrary/bibdata/blob/9a9e6ea96019abc180dd83f4ad03289d211562b9/spec/marc_to_solr/lib/config_spec.rb#L413-L448

**Comment by christinach** [comment]
I exported from alma, a record with mms_id: 9976174773506421. In 852 it has no subfield z. We use it for the location_notes. It is not included in the Publishing Profile -> Data enrichment (Physical Holding enrichment). @mzelesky do we need to include 852$z in the enrichment and index it in the holdings1_display? 

Also the 856$z and 856$u include the information that should display in the 'Available Online' section. 951$i and $x include the information but we dont extract them in the electronic_portfolio_s. We only extract 951$k 951$n 951$x. https://github.com/pulibrary/bibdata/blob/f62685cc8b1040dfaca267c4819a16080b849ea4/marc_to_solr/lib/traject_config.rb#L1327 
Can we discuss this when you have a chance? 

(I remember that we reverted the work of adding the location note through the api call on the item level because it was expensive; but this is different.)

**Comment by christinach** [comment]
I'm not sure if there was a change but this record is looking ok now https://catalog-alma-qa.princeton.edu/catalog/9976174773506421

**Comment by christinach** [comment]
Probably when I was checking the record, catalog alma qa was pointing to an older index. But now I can see the electronic portfolio and the electronic one display.

**Comment by christinach** [comment]
https://catalog.princeton.edu/catalog/7617477/
https://catalog-alma-qa.princeton.edu/catalog/9976174773506421/
I still have a question for the location note. 852$z. that is not in the exported record. @mzelesky
