### ISSUE TITLE
Items in locations where flag "aeon_location" is true should have availability "Onsite access only"

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1314]
They currently show as "some items not available" because they have no item records (no barcodes)

Example: https://catalog-alma-qa.princeton.edu/catalog/9917917633506421
 
For these items, locations are indexed so availability calls are not needed / availability status can be set and not updated. Alternately, bibdata could return "Online access only" to keep business logic all in one place.

**Comment by kevinreiss** [comment]
This would be a good, clean solution that would let us dump a bunch of code from the catalog. Although if we are concerned about reducing some load on the Alma API we could have Blacklight handle processing the display of any location flagged for Aeon on the server side since the catalog knows what is or isn't Aeon location because it's loading the holding_location configuration values, particularly on the search results page.

**Comment by christinach** [comment]
Do we want `Onsite access only` or `Onsite access`

**Comment by kevinreiss** [comment]
We have "On-site access" in prod now. Let's go with that.

**Comment by christinach** [comment]
Thank you @kevinreiss

**Comment by hackartisan** [comment]
We should do this in the availability response as a first step.
