### ISSUE TITLE
Thesis are index with a holding location of mudd, but no location of just mudd exists

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/bibdata#1368]
Just plain `mudd` does not exists in https://bibdata-alma-staging.princeton.edu/locations/holding_locations

The location code here is `mudd` https://catalog-alma-qa.princeton.edu/catalog/dsp01rr1720547/raw. 

This mismatch is causing issues for requests.  I'm guessing it will cause issues for other places, but I am uncertain.

I should also note that the https://catalog-alma-qa.princeton.edu/catalog/dsp01rr1720547 does not have a request button, where https://catalog.princeton.edu/catalog/dsp01rr1720547 has a reading room button.  Maybe the request app can stop worrying about thesis all together?

**Comment by christinach** [comment]
The file that we used to index the theses has the current production location (which is an issue as @carolyncole said). We could update the theses.json file with the correct location if we know which one it is. @kevinreiss @mzelesky is there a way for them to update the location so that when we pull the theses.json file to have the updated mud location? 
Or if I can update the file locally, what is the location that we should have mudd$cat, mudd$circ, mudd$mic, mudd$prnc, mudd$stacks, mudd$UNASSIGNED (adding it since it is in the locations)?

**Comment by christinach** [comment]
We have thesis that are online and have the elf location in production. 

https://catalog-alma-qa.princeton.edu/?page=1&q=id%3Adsp%2A&search_field=all_fields&utf8=%E2%9C%93

Also theses that are in the library have label 'Mudd Manuscript Library' which in the alma-qa locations is the `mudd$UNASSIGNED`

**Comment by christinach** [comment]
the location code for online and physical in these is handled in: https://github.com/pulibrary/orangetheses/blob/ab605df8dc3a810571e85e4b0baddd42157dd5ef/lib/orangetheses/indexer.rb#L145-L169

**Comment by christinach** [comment]
Maybe we can update ^ with the correct location and generate again the theses file and reindex in alma-staging. The question is what the locations should be?

**Comment by christinach** [comment]
Based on the voyager mapping file https://docs.google.com/spreadsheets/d/18YCL_PoGMjybNHplVpVhdk-fEgPrTHHxU2VvNcpOTBI/edit#gid=0 `mudd` should be updated to `mudd$stacks`.

We don't have online locations anymore. We need to think about the online location replacement.

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/orangetheses/pull/59
