### ISSUE TITLE
Items in Resource Sharing Process Type cause errors in some Availability Lookups

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#1374]
Items that fall into the Alma Process Type "Resource Sharing Request" seem to error out and give back 500s on both the record page and search results. They work fine when the holding ID is included and correctly identify themselves as a "Not Available' item for the request form. Example:

MMS ID - 99101217653506421
https://catalog-alma-qa.princeton.edu/catalog/99101217653506421
https://catalog-alma-qa.princeton.edu/requests/99101217653506421?mfhd=22172642960006421&source=pulsearch

This is the process type that our items we send out to other libraries get.

**Comment by hectorcorrea** [comment]
The issue here is that the Alma API returns no `holding_id` when we make the call with the MMS ID. Since we don't get a `holding_id` we consider this an item in a temporary location and try to see if there is a copy available via CDL. The error is happening during this CDL.

We should not be making this CDL check in this case.
