### ISSUE TITLE
SCSB dump files empty

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/bibdata#1421]
All the files reported in https://bibdata-alma.princeton.edu/events are empty. 

For example, the file for `2021-05-22 6:00:05am` points to https://bibdata-alma.princeton.edu/dumps/5.json, that JSON file in turn points to dump file https://bibdata-alma.princeton.edu/dump_files/40 

The content of the dump file (once unzipped) it is 

```
{"inv_xml":[],"tab_newline":[],"leader":[],"composed_chars":[],"bad_utf8":[]}
```

I am not sure if this is an error or not but Christina asked me to log it as such :)

**Comment by christinach** [comment]
I checked the aws production and there are incremental files.

**Comment by tpendragon** [comment]
I think this is because prod isn't hooked up to the SCSB production bucket yet (didn't want to push partner updates out from these boxes.)

See https://github.com/pulibrary/princeton_ansible/blob/c7bce40ad04daa1048ff84a89d4803bae18f6998/group_vars/bibdata/alma_production.yml#L97-L102

vs 

https://github.com/pulibrary/princeton_ansible/blob/c7bce40ad04daa1048ff84a89d4803bae18f6998/group_vars/bibdata/production.yml#L127-L134

**Comment by christinach** [comment]
These are not the Princeton recap but the Recap Partner files we pull from SCSB.

**Comment by tpendragon** [comment]
Yes, I know, but the SCSB bucket configuration comes from the same place.

**Comment by christinach** [comment]
yes I see what you are saying. That it is disabled so that we dont submit princeton files to recap.

**Comment by hackartisan** [comment]
Ah, that makes sense. Then I think we may need to split out configuration for reads vs. writes. Because we need to be able to pull in the partner data and index it before we are able to push our own data.

**Comment by hackartisan** [comment]
Do we even want an Event if there are no relevant files to attach to it? If not, the code to look at is in the Dump model.

**Comment by hackartisan** [comment]
This seems low impact -- getting an error when trying to update the index with no data.
