### ISSUE TITLE
Slow loading of reserve locations

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1616]
**Issue**: Slow loading of reserve locations. Ex: https://catalog.princeton.edu/catalog/9960099173506421
**Impact**: Circulation/Reserve staff ask if there is anything we can do about the slow load time of the messaging about reserves. Takes maybe 4-8 seconds on average to display that information.

**Proposed solutions**: When the record from the publishing job includes the current location index it over the permanent location. https://github.com/pulibrary/bibdata/issues/1616

**Comment by hectorcorrea** [comment]
Some background information on how the Availability calls to bib data and Alma work in this scenarion.

The current Orangelight code makes one call to bibdata to get information about availability (https://bibdata.princeton.edu/bibliographic/availability.json?deep=true&bib_ids=9960099173506421) and the response looks as follows:

```
{
    "9960099173506421": {
        "fake_id_1": {
            "on_reserve": "Y",
            "location": "firestone$res3hr",
            "label": "Firestone Library - Circulation Desk (3 Hour Reserve)",
            "status_label": "Unavailable",
            "copy_number": null,
            "cdl": false,
            "temp_location": true,
            "id": "fake_id_1"
        }
    }
}
```

Notice that because the item is in a temporary location Alma returns no ID for the holding (hence the "fake_id_1" in the response). 

Since we don't have a valid holding id we make a second call to bibdata (https://bibdata.princeton.edu/bibliographic/9960099173506421/availability.json?deep=true) that forces bibdata to call the Alma **items API** to get the information. The response for this second call looks like this:

```
{
    "9960099173506421": {
        "22695150500006421": {
            "on_reserve": "Y",
            "location": "firestone$res3hr",
            "label": "Firestone Library - Circulation Desk (3 Hour Reserve)",
            "status_label": "Not Available",
            "copy_number": "1",
            "cdl": false,
            "temp_location": true,
            "id": "22695150500006421"
        }
    }
}
```

Notice that this response has the holding id (`22695150500006421`) rather than the fake placeholder. However, this second call is slow since the call to the Alma items API takes 2-3 seconds (on top of the 1second that the first call took!)

Some takeaways from this:

* Our use of the `deep=true` is a  bit confusing. Notice that both calls to bibdata pass `deep=true` but only the second one is slow because calling `/bibliographic/{id}/availability.json?deep=true` follows a different path than `/bibliographic/availability.json?deep=true&bib_ids={ids}`. My bad, mostly.

* Indexing the actual (temporary) location into Solr might be a good idea since we will be able to display to the user that information as soon as the page render.  But, we might still need to make a second (slow) API call to Alma to get the actual holding_id. This might be transparent to the user, though.

**Comment by mzelesky** [comment]
See https://github.com/pulibrary/bibdata/issues/1198 for some more discussion on this:

> Possible approach:
> 
> In parsing a MARCXML record from the publishing job, evaluate all items under each holding (linked by the subfield 0 in the 876 and the subfield 8 in the 852). If the item's current location (876|y and 876|z) is the same as the holding location, store the item under that holding ID.
> 
> If the item's current location is different from the holding location (the item is in a temp location), create a 'fake' holding for that location and store the item under that fake holding. Any subsequent items in that current location found on the bib record that differ from their parent holding locations also get stored under that fake holding. The same process needs to happen for all location variances found.
> 
> This will also allow us to show the items under a holding, which is a feature from Voyager we had to abandon.

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/bibdata/pull/1734
