### ISSUE TITLE
Deep Availability Lookups are Failing 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#1644]
Examples:

https://catalog.princeton.edu/catalog/99125379810406421
https://catalog.princeton.edu/catalog/99125379706706421

**Comment by kevinreiss** [comment]
Another example: https://catalog.princeton.edu/catalog/9975711613506421

**Comment by hectorcorrea** [comment]
The problem is that bibdata is raising error "Multiple items found under the same key" from this part of the code: https://github.com/pulibrary/bibdata/blob/main/app/adapters/alma_adapter/availability_status.rb#L25-L39 for these records.

I took a quick look at the data that comes from Alma for one of the offending records (mms id: `99125379706706421`) and it has two holdings and each holding with two items. It is strange that the holding information for one of the holdings (`22897390520006421`) is different depending on where it comes in the response, in one instance it has information about a temp location for reserves whereas in the other it does not...for the exact same holding.

More to come.

**Comment by hectorcorrea** [comment]
The culprit is that we return the availability information grouped by `mms_id` + `holding_id` and in this case there are **multiple items** for the same the `mms_id` + `holding_id` combination. In hindsight is an expected scenario but the code explicitly throws and exception when it happens because we had not decided what to do in this case (e.g. what is the availability of holding X if item X1 is available but item X2 is unavailable).

I'll submit a PR with some ideas.
