### ISSUE TITLE
Newly activated Electronic Portfolios are Not Displaying

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#1669]
Example: https://catalog.princeton.edu/catalog/99125130903306421

A portfolio was activated for this resource last week but is not displaying in the catalog.

**Comment by christinach** [comment]
probably related to https://github.com/pulibrary/bibdata/issues/1662

**Comment by christinach** [comment]
I checked in Alma the Modification Date for the portfolios of this record. 
portfolio 'Nexus Uni' has modification date:  `07/15/2021 06:53:17 EDT`
The second portfolio that is not indexed (yet) was modified on : `09/23/2021 11:14:24 EDT`

**Comment by christinach** [comment]
The portfolios are not displaying because sidekiq is still trying to index incremental_15001905180006421_20210923_020921[050]_new.tar.gz from 09/22 22:50. So far it has tried 18 times. The next retry will be in 8 hours. 

![Screen Shot 2021-09-27 at 3 28 21 PM](https://user-images.githubusercontent.com/9905193/134972397-aeaa0ed9-b535-4e3a-844d-d0180e2f029e.png)

In this case we need to wait and see why it's failing to index this dump file. 
As a result the rest of the batches are waiting for this dump to index successfully.

**Comment by christinach** [comment]
This is fixed now. The files were processed and indexed.
