### ISSUE TITLE
Extract Augment the Subject and Change the Subject into a gem

### ISSUE THREAD

**Issue by bess** [pulibrary/bibdata#1692]
Take the subject term lists and basic behavior from Augment the Subject and Change the Subject in bibdata and extract these into a gem.

**ACCEPTANCE CRITERIA**
- [ ] There is a published gem that can be used by bibdata to replicate the current functionality
- [ ] There is enough documentation with the gem that it could be used by another project (e.g., pulfalight)

**Comment by sandbergja** [comment]
Closing for now, since ChangeTheSubject is now in [its own gem](https://github.com/pulibrary/change_the_subject).

When we have a specific use case for converting the AugmentTheSubject work into a gem, we can open a new ticket, and have the discussions about how to make it work best for the use case (e.g. whether it should be its own gem, or the same gem as ChangeTheSubject).
