### ISSUE TITLE
Update Augment the Subject List with new Recommendations

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#1863]
Per Minjie Chen there is an updated list of terms we should use for the augment the subject list for indigenous studies. 

Updated term list is at: https://docs.google.com/spreadsheets/d/1jFsLExGilXWmXEikliuYUtdipF5HnRbNMZn-rgJYflY/edit#gid=1600276075

Add these to this file: https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/augment_the_subject/indigenous_studies.txt

Once added if it is possible we should do a selective publishing job in Alma that will force any records containing these terms through the updated term list. If that isn't practical given the large number of new terms we will have to catch up with a full re-index.

**Comment by carolyncole** [comment]
The big question is how did these terms become irrelevant in the first pass: https://github.com/pulibrary/bibdata/compare/what-to-remove-augment?expand=1#diff-ef2847b31f19f0c655e4cc5e4a332f3f94d6cca8aaec0987c4af1f8ff655dc31R169

We will need to figure out how to remove the irrelevant  (see: https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/augment_the_subject.rb#L87-L90 )

**Comment by christinach** [comment]
@kevinreiss will schedule a meeting with Minjie and our team to discuss further on this work.

**Comment by carolyncole** [comment]
This needs to be left to right matching.  There can be more terms after the term in the list, but the term(s) priori must match exactly (all terms)

**Comment by maxkadel** [comment]
Deployed to staging - waiting for feedback from Minjie Chen

**Comment by minjiec** [comment]
_(1) https://catalog-staging.princeton.edu/catalog/99105697413506421_
Looks great!

_(2) https://catalog-staging.princeton.edu/catalog/9946897643506421 (we wondered if not including the "Indigenous Studies" heading on this one is correct?)_
Aww this gets into the weed of cataloging rules. In this bib record, the subject heading of intererst is the following:

> White people—Canada—Relations with Indians—History

The LCSH string in LC's database, in contrast, is **White people—Relations with Indians** 
Now LC indicates that it's not allowed to attach geographical subdivision after the string. (Why? If I knew I guess I'd be working at LC...)
To get around the restriction, catalogers who wish to provide finer detail insert the geographical marker in between "White people" and "Relations with Indians," meaning such records would slip out of our left-match mechanism. My estimate is that the tagging would miss up to half of the bibs (around 200) with "Relations with Indians" in them due to the insertion. The number may be smaller if the bib contains other 650 that left-match other LC strings. See these examples I found in the bibs:

> $aWhite people--$zAlabama--$xRelations with Indians
> $aWhite people--$zCanada--$xRelations with Indians
> $aBlack people--$zCaribbean Area--$xRelations with Indians.
> $aBlack people--$zGeorgia--$xRelations with Indians.
> 
> $aWhites--$xSources.--$y19th century--$xRelations with Indians
> $aAfrican Americans--$zFlorida--$zFranklin County--$xRelations with Indians.
> $aWhite people--$zIllinois--$zChicago--$xRelations with Indians.
> $aWhite people--$zOntario--$zRainy River (District)--$xRelations with Indians.
> 

There are two options for you to consider.
First, stick with left matching and live with the (small) losses.

Second, use a seperate matching mechanism. Note that there is a second sheet named [Additional subfields](https://docs.google.com/spreadsheets/d/1jFsLExGilXWmXEikliuYUtdipF5HnRbNMZn-rgJYflY/edit#gid=1600276075) in the vocabulary list.

> ǂx Indian authors
> ǂx Indian influences
> ǂx Indian interpretations
> ǂx Indian languages
> ...


The presence of these topical divisions alone is suffcient to determing the relevance of the bibs to Indigenous Studies--unlike other subdivisions we talked about at our meeting on 05/27 and which Carolyn listed on [a page](https://github.com/pulibrary/bibdata/compare/what-to-remove-augment?expand=1#diff-ef2847b31f19f0c655e4cc5e4a332f3f94d6cca8aaec0987c4af1f8ff655dc31R169) linked above.

Would you be able to catch these subdivisions alone? Left-match from the start of the 650 field doesn't apply here, but the subfield x in bibs does need to match the terms in their entirety. For example, the first one is "ǂx Indian authors".  If a bib contains "ǂx **East** Indian authors" in 650, then it is not a match.

_(3) https://catalog-staging.princeton.edu/catalog/997737533506421 (did not previously have heading, now does)_
Looks great!
Thanks!

In replying to @maxkadel's Slack message -

> an updated version for Augment the Subject has been deployed to catalog-staging. We've only indexed a few example records.For example:
> •	https://catalog-staging.princeton.edu/catalog/99105697413506421
> •	https://catalog-staging.princeton.edu/catalog/9946897643506421 (we wondered if not including the "Indigenous Studies" heading on this one is correct?)
> •	https://catalog-staging.princeton.edu/catalog/997737533506421 (did not previously have heading, now does)
> Let us know how it looks, and if there are any other examples from the catalog you would like us to test.
>

**Comment by minjiec** [comment]
There is a fourth issue I'd like to bring about. I just realize that LC revised the following two terms this year --
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/minjiec/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/minjiec/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Old LCSH term | Current form
-- | --
Blacks—Relations with Indians | Black people ǂx Relations with Indians
Whites—Relations with Indians | White people ǂx Relations with Indians


</body>

</html>

I'll add "people" to the [spreadsheet](https://docs.google.com/spreadsheets/d/1jFsLExGilXWmXEikliuYUtdipF5HnRbNMZn-rgJYflY/edit#gid=1600276075), is that okay?
Thanks!
Minjie

**Comment by maxkadel** [comment]
Sure - changing those two subject headings should be relatively easy. 

I'm working on a ticket to follow up on the subject headings that are not left matching but should probably included the added subject heading.

**Comment by maxkadel** [comment]
@minjiec - see https://github.com/pulibrary/bibdata/issues/1889 as a follow-up. Does it seem reasonable to go forward with the code for now as-is, and then prioritize the linked ticket separately?

**Comment by minjiec** [comment]
Max, first, thank you for planning on working out a solution for those subdivisions!

Second, I have a curve ball for you. In column D "Left match" there are four values -

> 600 - personal name
> 610 - corporate body
> 650 - topical term
> 651 - strings that start with a geographical name

I think we have taken care of LCSH matching 650 fields very well. I wonder how other types of strings are matched. They are definitely in the numerical minority. If I have to choose, I think it'll be desirable to include 651 at least. Here is an example.
The string "Québec (Province)—History—Native Crisis, 1990" would be cataloged in the 651 field. As you can see from the staff view of the bib record [99125157701106421](https://catalog-staging.princeton.edu/catalog/99125157701106421/staff_view)

Would you have a quick solution for matching vocabulary up with bib fields other than 650 as well? Please let don't hesitate to let me know if I can provide more explanation.

Minjie

**Comment by maxkadel** [comment]
@minjiec This did help me find a bug with it not matching subject headings with parentheses in them, but we *are* capturing headings in 600, 610, 611, 630, 650, 651. See https://catalog-staging.princeton.edu/catalog/9937484443506421/ for a working example. 

Note: we haven't run the updated code on the full index yet, so there will be other examples that aren't updated yet, but we can run them individually

**Comment by minjiec** [comment]
Max, I am thrilled to know that your match is capturing other 65x fields than 650. Then all looks good!

**Comment by maxkadel** [comment]
@minjiec - I just wanted to update you on this - the code was working on individual objects, but unfortunately, when we tried to scale it up to reindexing all of staging, in preparation for production, we hit a showstopper bug, which has been very difficult to investigate beyond "sometimes indexing breaks on the augment the subject code". 

We're still working on it, and I'm hopeful we'll figure out the fix in the next week or two, but it's still in process. 

The examples you gave above will be helpful in testing - thank you.

**Comment by maxkadel** [comment]
@minjiec - Is the line below correct? It seems like maybe anything with "Koniagmiut Eskimos" should include the "Indigenous Studies" subject heading?
```
Koniagmiut Eskimos—Anthropometry	y	[150]	650	Koniagmiut Eskimos ǂx Anthropometry
```

**Comment by maxkadel** [comment]
@minjiec - we've deployed a different way of doing the Augment the Subject code, and just finished running a re-index on the staging environment. Would you be able to look at some records and see if they're appearing as you'd expect? They would be on https://catalog-staging.princeton.edu/

**Comment by minjiec** [comment]
@maxkadel, I spot-checked various string types and can see how currently not-tagged bibs are showing the "indigenous studies" tag in Staging. All looks good to me. Thank you for coming up with the solution!

**Topical subdivision**:	[$x Indian influences](https://catalog-staging.princeton.edu/catalog/9914669173506421) vs. [current Blacklight](https://catalog.princeton.edu/catalog/9914669173506421)

**650$a**:	[Aymara women](https://catalog-staging.princeton.edu/catalog/99107587303506421) vs. [current Blacklight](https://catalog.princeton.edu/catalog/99107587303506421)

**650 string**:	[Cooking, Canadian--Nunavut style](https://catalog-staging.princeton.edu/catalog/9937160023506421) vs. [current Blacklight](https://catalog.princeton.edu/catalog/9937160023506421)

**651$a**:	[Bering Land Bridge](https://catalog-staging.princeton.edu/catalog/99114721873506421) vs. [current Blacklight](https://catalog.princeton.edu/catalog/99114721873506421)

**651 string**:	[Connecticut—History—French and Indian War, 1754-1763](https://catalog-staging.princeton.edu/catalog/9924983083506421) vs. [current Blacklight](https://catalog.princeton.edu/catalog/9924983083506421)

**610 string**:	[United States. Army—Indian troops](https://catalog-staging.princeton.edu/catalog/9974376293506421) vs. [current Blacklight](https://catalog.princeton.edu/catalog/9974376293506421)

**Comment by maxkadel** [comment]
@minjiec  - the code we have expects the format of the file as it is right now in Google Drive (especially the first worksheet). Is this something that you / the working group can keep consistent? Adding fields shouldn't be an issue, but deleting fields or changing the headers could cause problems.

**Comment by minjiec** [comment]
@maxkadel I'll keep it in mind--that deleting fields or changing the headers could cause problems. There hasn't been a plan on the routine maintenance of the list.
