### ISSUE TITLE
Index homosaurus subject headings ($2homoit)

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/bibdata#1925]
User story 1: as a catalog user, I would like to search for records using terms in the homosaurus vocabulary.
User story 2: as a catalog user, I would like to see homosaurus vocabulary terms display in record show pages.

homosaurus vocabulary terms can be identified in the marc record by the combination of:

- Tag 650
- Second indicator 7
- Subfield 2 with a value "homoit"

@kevinreiss is going to get some more clarity and prioritization of this ticket.

This will probably require a full re-index.

Companion ticket in Orangelight: https://github.com/pulibrary/orangelight/issues/3078 -- we may also need a ticket in pul_solr to weight this search field appropriately.

**Comment by kevinreiss** [comment]
Example record in production: https://catalog.princeton.edu/catalog/99125407041106421

**Comment by christinach** [comment]
@mzelesky suggested to add in bibdata the `homoit_s` so that we indicate in the record page the source of the term. previous example for lcgft_shttps://github.com/pulibrary/bibdata/pull/471/files. 
@mzelesky also suggests to revisit https://github.com/pulibrary/orangelight/pull/3029 as part of this work.
