### ISSUE TITLE
Add Lewis as a Pick-up Option for Plasma Physics Items

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#2043]
### User story
Allow Plasma Physics locations to only have Lewis Library as a pickup location. We will be treating all these items as if they are in the Lewis Library. 

### Concrete example
https://catalog.princeton.edu/catalog/99117069583506421

### Re-index required?

- [ ] Full re-index
- [ ] Partial re-index
- [x] No re-indexing required

### Implementation notes, if any

There are 12 plasma locations. We will need to enable this for all of them. 

- [x] Make Plasma Phyics Library an "open" library again
- [x] Update delivery location options for plasma locations to have Lewis Library as the delivery option. https://bibdata.princeton.edu/locations/delivery_locations/14
- [x] Confirm with Mark Z/Peter that Alma will accept a hold request for PPPL items delivered to Lewis

**Comment by christinach** [comment]
This is blocked until further update from @kevinreiss

**Comment by christinach** [comment]
@kevinreiss do we want to close this issue? I noticed you closed https://github.com/pulibrary/orangelight/pull/3288

**Comment by mzelesky** [comment]
Per the Circulation meeting on 1-18-23, Lewis should be the only pickup location for PPPL materials.

**Comment by christinach** [comment]
@kevinreiss do we need to update [plasma$nb](https://bibdata.princeton.edu/locations/holding_locations/plasma$nb)  and [plasma$stacks](https://bibdata.princeton.edu/locations/holding_locations/plasma$stacks)  to have only Lewis as well?

**Comment by kevinreiss** [comment]
Any location at https://bibdata.princeton.edu/locations/holding_locations where library=plasma and requestable=true should have lewis set as the pick-up location.

**Comment by christinach** [comment]
I've populated the locations both in bibdata-qa and bibdata-staging.

**Comment by pmgreen** [comment]
As it stands in the sandbox config:
- Lewis circ desk has a hold shelf and (under 'Relationships') is configured to circulate for all (libraries)
- PPPL is configured to deliver to all (libraries) (also tried a relationship explicitly delivering to Lewis)
- There's an experimental Requests rule in the General FU called 'PPPL request rule' pointing to a new Requests TOU called 'PPPL Requests' that allows for `Pickup - Anywhere` (rather than the default of `Must pickup in owning library`)
- Example request is still failing with `There was a problem with this request which Library staff need to investigate. You'll be notified once it's resolved and requested for you.`: https://catalog-qa.princeton.edu/requests/99122372723506421?aeon=false&mfhd=22573090520006421
- Through Alma, the request seems to be successful:
<img width="515" alt="Screen Shot 2023-03-30 at 12 43 27 PM" src="https://user-images.githubusercontent.com/2067241/228907311-d8b7e079-1bc9-440f-abd3-d70afff4ac2e.png">
<img width="123" alt="Screen Shot 2023-03-30 at 12 52 14 PM" src="https://user-images.githubusercontent.com/2067241/228909293-5c057732-885e-46f4-8994-40f2d896d4e2.png">
<img width="1140" alt="Screen Shot 2023-03-30 at 12 45 26 PM" src="https://user-images.githubusercontent.com/2067241/228907381-6714029a-9b68-47e4-8beb-07aada03f0e2.png">

**Comment by christinach** [comment]
@pmgreen I should have mentioned that https://catalog-qa.princeton.edu/requests/99122372723506421?aeon=false&mfhd=22573090520006421 is pointing Alma production. 

catalog-staging is pointing the Alma sandbox https://catalog-staging.princeton.edu/requests/99122372723506421?aeon=false&mfhd=22573090520006421 but as far as I remember in general we cannot place a request though catalog-staging against the alma sandbox.

**Comment by christinach** [comment]
@pmgreen thanks for checking . I checked again my library card in the alma sandbox and I can see my request with pick library Lewis.
![Screenshot 2023-03-30 at 1 18 18 PM](https://user-images.githubusercontent.com/9905193/228914809-5b3abff3-3e6d-498d-9900-aae01ea89059.png)

**Comment by pmgreen** [comment]
@christinach : @mzelesky and I have implemented configuration in prod

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/bibdata/pull/2114
