### ISSUE TITLE
Running the full SCSB reindex it's indexing old daily scsb updates. 

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#2294]
### Expected behavior
When running the scsb full index task, the index should index the files from the latest 'Full Partner ReCAP Records' dump and continue indexing daily scsb updates. 

### Actual behavior
When we run the full scsb reindex it's indexing old daily scsb updates. 

### Steps to replicate
Run the full scsb reindx task 

### Impact of this bug
Old files and updates are getting indexed. 

### Re-index required?

- [ ] Full re-index
- [ ] Partial re-index
- [ ] No re-indexing required

**Comment by sandbergja** [comment]
I believe this happened because the most recent full dump in prod (ID 4309), while it has a created_at of January 13th, has a generated_date of January 1.  Compared to 4309, incremental 4271 has a created_at of January 6, so it seems like an old update to us.  However, its generated_date is January 5, so the rake task considers it to be more recent than the full dump.

**Comment by sandbergja** [comment]
@christinach and I looked at this today.  The generated_date of January 1 is expected (this is when PUL requested the dump via the SCSB API).  This does not explain the very old incrementals (e.g. from 2 years ago) that were being indexed before.  However, since those incrementals have been deleted now, we'll close this issue for now, and troubleshoot further if it happens again.
