### ISSUE TITLE
Automatically clean up the /alma directory

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/bibdata#2401]
### User story
The /alma directory has a lot of old files and is using too much disk space. We should setup an automated job to clean up old files.

### Acceptance criteria

Create a periodic task to delete files that have been on the disk more than x months

- [ ] Create a tasks to clean up files in the /alma directory
- [ ] Schedule this task to run as a scheduled task

**Comment by kevinreiss** [comment]
Related issue https://github.com/pulibrary/lib_jobs/issues/795

**Comment by acozine** [comment]
The `/alma/*` directories live on the `lib-sftp-*` servers. Both lib-jobs and bibdata access the directories. If we put the cleanup task in the SFTP role, aka `roles/system_ldap`, it should apply to all projects that access Alma data.

**Comment by kevinreiss** [comment]
@mzelesky what should be our cut-off date for purging old files? Three months from today?

**Comment by mzelesky** [comment]
In general, 3 months is a good rule, except for the following directory:

`/alma/invoices`: 1 year, since I just uncovered that Alma recalculates expenditures for foreign currencies when it shouldn't; the invoice export is the only way I have as of now to find out what we submitted to Prime for payment
