### ISSUE TITLE
Support SCSB Transfer API

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#249]
Transfer of holding or item level data to a new bibliographic record will be initiated by Princeton circulation staff. HTC will provide a new API endpoint available for transfers.

**Comment by kevinreiss** [comment]
API is now available for testing https://uat-recap.htcinc.com:9093/swagger-ui.html#!/shared-collection-rest-controller/transferHoldingsAndItems.

**Comment by kevinreiss** [comment]
@mzelesky Does this need to be implemented as a rake task that takes a csv or json file as input or as a web form staff can use?

**Comment by mzelesky** [comment]
I think a web form is the best, so Marie's staff have less of a learning curve.

**Comment by mzelesky** [comment]
A CSV as input has more room for error.

**Comment by kevinreiss** [comment]
Staff need a web form this. Two types of transfers
1. An Item moved from one holding to another on the same bib
2. An item moved from one holding to another on a different bib
2. A holding moved from one bib record to another bib record

**Comment by mzelesky** [comment]
Lines 1 and 2 use the same mechanism on the SCSB side. For scenarios 1 and 2, the data provided by the user could be the same (provide old bib, holding, and item ID, and new bib, holding, and item ID). To make it even simpler, since the item ID should never change, there could be just one item ID box, which the form submits to SCSB in both the set of old IDs and the set of new IDs.
