### ISSUE TITLE
Test due date variations in availability controller

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#794]
There's a test claiming some variation based on due date, but the test itself isn't related to whatever variation the comment is referencing. I'm removing the note. Perhaps if there is some variation based on due date we can add in a different test down the road. Leaving this issue here for now.

https://github.com/pulibrary/marc_liberation/blob/a12df0a37eb1df7e155142897fed49a01f33a9b3/spec/controllers/availability_controller_spec.rb#L210

**Comment by christinach** [comment]
The logic of how the due_date is displayed is not obvious in marc_liberation. I added the comment in the test so that I remember not to add the due_date in a test where the due_date is more that 30 days from now. 
But yes it can be removed as a comment and we can add a new test to test the due_date on the availability. I'll open an issue for that.

**Comment by christinach** [comment]
No I will not add a new issue we can use this one for adding a spec.

**Comment by christinach** [comment]
This is where it is coming from https://github.com/pulibrary/voyager_helpers/blob/37b62ad83ed2f1af6185e54534d901e23e5fdf30/lib/voyager_helpers/liberator.rb#L699

**Comment by christinach** [comment]
Examples for the due_date spec:
**1. bib_id: 189356**
- item_id: 202844
- current_due_date: 2020-09-15 23:59:00
- https://catalog.princeton.edu/catalog/189356 with status display: `checked_out`
- The availability **includes** the due_date because it is in the last 30 days range from today (09/17/2020) https://bibdata.princeton.edu/availability?id=189356 with `status: Overdue`

**2. bib_id: 5655647**
- item_id: 5261955
- current_due_date: 2020-08-15 21:00:00
- https://catalog.princeton.edu/catalog/5655647 with status display: `checked_out`
- The availability **does not include** the due_date because it is older than the 30 days range from today (09/17/2020) 
 https://bibdata.princeton.edu/availability?id=5655647 with `status: Overdue`

**Comment by christinach** [comment]
related #744

**Comment by hackartisan** [comment]
We need to update this ticket with current examples, and include screen shots and cut / paste data from marc liberation so that we still see the important details when the objects are updated (i.e. renewed, or slide over into "long overdue")

Also add the "long overdue" use case?

**Comment by hackartisan** [comment]
we don't have due dates anymore
